/**
 * TypeScript interfaces for weather records stored in Supabase.
 *
 * WeatherRecord — a full row from the weather_records table
 * DailyTemp     — one element of the temperature_data JSONB array,
 *                 representing a single calendar day's weather summary
 */

export interface DailyTemp {
  date: string;                // YYYY-MM-DD
  temp_max: number | null;     // daily high (in the record's unit system)
  temp_min: number | null;     // daily low
  temp_avg: number | null;     // midpoint of high and low
  precipitation: number | null; // total precipitation in mm
  windspeed_max: number | null; // max wind speed in km/h (Open-Meteo default)
}

export interface WeatherRecord {
  id: string;                  // UUID primary key generated by Supabase
  location_query: string;      // original text the user typed in the form
  city_name: string;           // resolved city name from geocoding
  country: string | null;      // two-letter country code (null if coordinates were used)
  latitude: number;
  longitude: number;
  start_date: string;          // YYYY-MM-DD
  end_date: string;
  temperature_data: DailyTemp[]; // one entry per day in the range
  units: 'imperial' | 'metric';
  notes: string;               // optional user-supplied note
  created_at: string;          // ISO timestamp set by Supabase on insert
  updated_at: string;          // ISO timestamp updated automatically by a DB trigger
}
